#!/usr/bin/env python3
"""Port the step shell out of template.html into the Next.js app.

Splits the template into:
  platform/app/steps/[slug]/step.css        — the design system CSS
  platform/public/step-client.js            — the behavior JS (tap-define,
                                               tickable outcomes, rate/complete,
                                               scroll-reveal), reading per-step
                                               data from window.__STEP__
  platform/app/steps/[slug]/shell-parts.json — icon sprite, tip div, voice orb

Run whenever template.html changes (until the template is retired at cutover):
    python3 _dev/step-generator/port_shell.py
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
TPL = (HERE / "template.html").read_text(encoding="utf-8")
VOICE = (HERE / "voice_placeholder.html").read_text(encoding="utf-8")

OUT_CSS = ROOT / "platform" / "app" / "steps" / "[slug]" / "step.css"
OUT_JS = ROOT / "platform" / "public" / "step-client.js"
OUT_PARTS = ROOT / "platform" / "app" / "steps" / "[slug]" / "shell-parts.json"


def between(s, start, end, label):
    i = s.index(start) + len(start)
    j = s.index(end, i)
    assert i > len(start) - 1 and j > i, f"could not slice {label}"
    return s[i:j]


# ── CSS ──────────────────────────────────────────────────────
css = between(TPL, "<style>\n", "\n</style>", "css")
# Scope the body rule to step pages only, so the design doesn't leak onto
# other routes (/steps index, /pricing) during client-side navigation.
assert "  body {" in css, "body rule moved — update port_shell.py"
css = css.replace("  body {", "  body:has(.step-shell) {", 1)
header = (
    "/* GENERATED by _dev/step-generator/port_shell.py from template.html.\n"
    "   Do not edit by hand — edit the template and re-run the porter. */\n"
)
OUT_CSS.parent.mkdir(parents=True, exist_ok=True)
OUT_CSS.write_text(header + css + "\n", encoding="utf-8")

# ── JS ───────────────────────────────────────────────────────
js = between(TPL, "</div>\n\n<script>\n", "\n</script>", "js")
subs = [
    ("var BRAND = {{BRAND_JSON}};",
     "var BRAND = (window.__STEP__ || {}).brand || {};"),
    ("var GLOSSARY = {{GLOSSARY_JSON}};",
     "var GLOSSARY = (window.__STEP__ || {}).glossary || {};"),
    ('var STEP = "{{STEP_SLUG}}";',
     'var STEP = (window.__STEP__ || {}).slug || "";'),
    ("{{CALCULATOR_JS}}", ""),  # per-step JS runs as its own inline script
]
for old, new in subs:
    assert old in js, f"JS anchor missing: {old[:40]}"
    js = js.replace(old, new)
js_header = (
    "/* GENERATED by _dev/step-generator/port_shell.py from template.html.\n"
    "   Per-step data arrives via window.__STEP__ = {slug, brand, glossary},\n"
    "   set by app/steps/[slug]/page.tsx before this script loads. */\n"
)
OUT_JS.write_text(js_header + js + "\n", encoding="utf-8")

# ── Shell parts (sprite, tip, voice) ─────────────────────────
sprite = re.search(r'<svg xmlns="http://www\.w3\.org/2000/svg" style="display:none".*?</svg>', TPL, re.S)
tip = re.search(r'<div class="tip" id="tip"[^>]*></div>', TPL)
assert sprite and tip, "sprite/tip anchors moved — update port_shell.py"
OUT_PARTS.write_text(json.dumps({
    "sprite": sprite.group(0),
    "tip": tip.group(0),
    "voice": VOICE,
}, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")

for p in (OUT_CSS, OUT_JS, OUT_PARTS):
    print(f"wrote {p.relative_to(ROOT)} ({p.stat().st_size} bytes)")
