/* ------------------------------------------------------------------ *
 * What each university teaches, by programme and by year.
 *
 * The knowledge behind a predictive sign-up (owner, 2026-08-04): "the moment
 * they say I'm at ZCAS doing accounting and finance in year four, I'll display
 * the year four courses, and below that the other years' courses… I'll do as
 * much to help them so they don't have to manually pick things."
 *
 * IMPORTED ONLY BY THE ONBOARDING ROUTE, and that is load-bearing. The file is
 * ~81KB of curriculum. lib/schools is pulled in by the identity store, which
 * loads on every page including the reader — this must never join it there, or
 * every student downloads 41 programmes to read one step. /onboarding is its
 * own route, so Next code-splits it there and nowhere else.
 *
 * Generated by scripts/gen-programmes.mjs from Supabase. Course codes and
 * faculty names are excluded at the view, not here — see the generator.
 * ------------------------------------------------------------------ */

import PROGRAMME_INDEX from "./programme-index.json";

/** One course on a programme's timetable. */
export type ProgrammeCourse = {
  /** The curriculum's own slug. Stable, and NOT the same namespace as a built
   *  course's slug — this identifies the course on the syllabus whether or not
   *  anybody has written it yet. */
  slug: string;
  title: string;
  /** Which year of the programme it is taught in. */
  year: number | null;
  /** The built course this maps to, where one exists. Absent is the normal
   *  case: 4 of 357 are built. A row without it still shows and can still be
   *  picked — see the note on demand below. */
  live?: string;
};

export type Programme = {
  slug: string;
  name: string;
  level: string | null;
  /** Years this programme actually publishes, ascending. Usually [1,2,3,4];
   *  a masters is [5,6]. Read off the data rather than assumed, because
   *  "year 1" means different things to an undergraduate and a postgraduate. */
  years: number[];
  courses: ProgrammeCourse[];
};

const INDEX = PROGRAMME_INDEX as Record<string, Programme[]>;

/**
 * The programmes a university publishes, or an empty list.
 *
 * EMPTY IS A NORMAL ANSWER, not a failure. Only ZCAS has been scraped so far,
 * so nine of the ten universities in the picker return nothing today — and the
 * flow is built to skip its programme and year questions when that happens
 * rather than showing an empty list. Filling those universities in later is a
 * data job with no code change, which is what the owner asked for: "set this up
 * so it works dynamically, i will be filling in those courses later."
 */
export function programmesFor(school: string | null | undefined): Programme[] {
  return (school && INDEX[school]) || [];
}

/** Whether asking "which programme?" can be answered at this university. */
export function hasProgrammes(school: string | null | undefined): boolean {
  return programmesFor(school).length > 0;
}

export function programmeBySlug(school: string | null | undefined, slug: string | null | undefined) {
  return slug ? programmesFor(school).find((p) => p.slug === slug) : undefined;
}

/**
 * A programme's courses split into the ones the student is taking now and the
 * rest — owner's layout: "I'll first display the year four courses, and then
 * below that I will display the other years' courses."
 *
 * The other years are kept and NOT hidden, because a student repeating a
 * module, or taking one early, is ordinary and the alternative is a list that
 * quietly refuses to contain their actual timetable.
 */
export function coursesByYear(programme: Programme | undefined, year: number | null | undefined) {
  if (!programme) return { thisYear: [], otherYears: [] };
  if (!year) return { thisYear: programme.courses, otherYears: [] };
  return {
    thisYear: programme.courses.filter((c) => c.year === year),
    otherYears: programme.courses.filter((c) => c.year !== year),
  };
}

/**
 * The built-course slugs behind a set of curriculum picks.
 *
 * The two lists are stored separately on the identity and this is the join.
 * A student ticks their real timetable — the owner's call, "show them literally
 * all the courses not just what we've built, that way we can prioritise
 * building properly" — so most picks have nothing behind them yet. The
 * dashboard must only ever be handed the ones that do, or it renders courses
 * with no content; the rest are kept as the demand signal that ranks what to
 * build next.
 */
export function liveSlugsFor(programme: Programme | undefined, picks: string[]): string[] {
  if (!programme) return [];
  const want = new Set(picks);
  return programme.courses.filter((c) => c.live && want.has(c.slug)).map((c) => c.live as string);
}

/** Every course this programme teaches that we have actually built. Used to
 *  tell a student what is ready without making them hunt for it. */
export function builtCount(programme: Programme | undefined): number {
  return programme ? programme.courses.filter((c) => c.live).length : 0;
}
