/* ------------------------------------------------------------------ *
 * What each university teaches, by programme and by year.
 *
 * The knowledge behind a predictive sign-up (owner, 2026-08-04): "the moment
 * they say I'm at ZCAS doing accounting and finance in year four, I'll display
 * the year four courses, and below that the other years' courses… I'll do as
 * much to help them so they don't have to manually pick things."
 *
 * IMPORTED ONLY BY THE ONBOARDING ROUTE, and that is load-bearing. The file is
 * ~81KB of curriculum. lib/schools is pulled in by the identity store, which
 * loads on every page including the reader — this must never join it there, or
 * every student downloads 41 programmes to read one step. /onboarding is its
 * own route, so Next code-splits it there and nowhere else.
 *
 * Generated by scripts/gen-programmes.mjs from Supabase. Course codes and
 * faculty names are excluded at the view, not here — see the generator.
 * ------------------------------------------------------------------ */

import PROGRAMME_INDEX from "./programme-index.json";

/** One course on a programme's timetable. */
export type ProgrammeCourse = {
  /** The curriculum's own slug. Stable, and NOT the same namespace as a built
   *  course's slug — this identifies the course on the syllabus whether or not
   *  anybody has written it yet. */
  slug: string;
  title: string;
  /** Which year of the programme it is taught in. */
  year: number | null;
  /** Which half of that year — 1 or 2, null where the source didn't say. */
  semester: number | null;
  /** The built course this maps to, where one exists. Absent is the normal
   *  case: 4 of 357 are built. A row without it still shows and can still be
   *  picked — see the note on demand below. */
  live?: string;
};

export type Programme = {
  slug: string;
  name: string;
  level: string | null;
  /** Years this programme actually publishes, ascending. Usually [1,2,3,4];
   *  a masters is [5,6]. Read off the data rather than assumed, because
   *  "year 1" means different things to an undergraduate and a postgraduate. */
  years: number[];
  courses: ProgrammeCourse[];
};

const INDEX = PROGRAMME_INDEX as Record<string, Programme[]>;

/**
 * The programmes a university publishes, or an empty list.
 *
 * EMPTY IS A NORMAL ANSWER, not a failure. Only ZCAS has been scraped so far,
 * so nine of the ten universities in the picker return nothing today — and the
 * flow is built to skip its programme and year questions when that happens
 * rather than showing an empty list. Filling those universities in later is a
 * data job with no code change, which is what the owner asked for: "set this up
 * so it works dynamically, i will be filling in those courses later."
 */
export function programmesFor(school: string | null | undefined): Programme[] {
  return (school && INDEX[school]) || [];
}

/** Whether asking "which programme?" can be answered at this university. */
export function hasProgrammes(school: string | null | undefined): boolean {
  return programmesFor(school).length > 0;
}

export function programmeBySlug(school: string | null | undefined, slug: string | null | undefined) {
  return slug ? programmesFor(school).find((p) => p.slug === slug) : undefined;
}

/** A year of a programme, and what it teaches. */
export type YearGroup = { year: number | null; courses: ProgrammeCourse[] };

/**
 * A programme's courses split into the ones the student is taking now and the
 * rest — owner's layout: "I'll first display the year four courses, and then
 * below that I will display the other years' courses."
 *
 * The other years are kept and NOT hidden, because a student repeating a
 * module, or taking one early, is ordinary and the alternative is a list that
 * quietly refuses to contain their actual timetable.
 *
 * THE REST STAYS GROUPED BY YEAR (owner, 2026-08-04: "when you let us know the
 * courses, can you please still categorize the other courses by years?"). It
 * was one flat list of everything-not-this-year — 24 rows for a year-4 student,
 * in which Principles of Accounting and Advanced Taxation sat next to each
 * other with nothing to say that one is a first-year course and the other a
 * third. The year is the only thing that makes a list that long navigable, and
 * we already know it for every row, so throwing it away at the last step was
 * the one place this flow stopped being predictive.
 *
 * Ascending, and the student's own year is not among them — it is `thisYear`.
 */
export function coursesByYear(programme: Programme | undefined, year: number | null | undefined) {
  if (!programme) return { thisYear: [], otherYears: [] as YearGroup[] };
  if (!year) return { thisYear: programme.courses, otherYears: [] as YearGroup[] };

  const thisYear = programme.courses.filter((c) => c.year === year);
  const rest = new Map<number | null, ProgrammeCourse[]>();
  for (const c of programme.courses) {
    if (c.year === year) continue;
    const k = c.year ?? null;
    rest.set(k, [...(rest.get(k) ?? []), c]);
  }
  /**
   * NEAREST YEAR FIRST, WORKING AWAY FROM THEIRS (owner, 2026-08-04: "organize
   * them from the older years to the younger years… if there are courses that
   * have been carried over, they'll be closer to the older years, and the
   * easier courses, the prerequisites, go to the bottom").
   *
   * The list is ordered by how likely a row is to be the one they came for. A
   * year-4 student with a carry-over is overwhelmingly carrying something from
   * year 3, not from year 1 — so the years below theirs run DOWNWARD from the
   * one they just finished, and first-year prerequisites end up furthest away.
   * Ascending put the least likely year at the top and made them scroll past
   * eight rows of Academic Writing to reach the module they actually failed.
   *
   * Years ABOVE theirs then follow, running upward — the same "nearest first"
   * rule, applied to the other direction. The owner's reasoning was about
   * carry-overs and so only names the years below; this extends it rather than
   * inventing a second rule, and it matters for the students they did not
   * mention: a year-1 student has nothing below them, and ordering their
   * "other years" downward from 6 would put the most distant year on top.
   *
   * A course with no year sorts last in either case. It is a gap in the scrape,
   * not a year zero, and it should not head anything pretending to be one.
   */
  const rank = (y: number | null): [number, number] =>
    y == null ? [2, 0] : y < year ? [0, -y] : [1, y];

  const otherYears: YearGroup[] = [...rest.entries()]
    .sort(([a], [b]) => {
      const [ba, ka] = rank(a);
      const [bb, kb] = rank(b);
      return ba - bb || ka - kb;
    })
    .map(([y, courses]) => ({ year: y, courses }));

  return { thisYear, otherYears };
}

/**
 * The built-course slugs behind a set of curriculum picks.
 *
 * The two lists are stored separately on the identity and this is the join.
 * A student ticks their real timetable — the owner's call, "show them literally
 * all the courses not just what we've built, that way we can prioritise
 * building properly" — so most picks have nothing behind them yet. The
 * dashboard must only ever be handed the ones that do, or it renders courses
 * with no content; the rest are kept as the demand signal that ranks what to
 * build next.
 */
export function liveSlugsFor(programme: Programme | undefined, picks: string[]): string[] {
  if (!programme) return [];
  const want = new Set(picks);
  return programme.courses.filter((c) => c.live && want.has(c.slug)).map((c) => c.live as string);
}

/** Every course this programme teaches that we have actually built. Used to
 *  tell a student what is ready without making them hunt for it. */
export function builtCount(programme: Programme | undefined): number {
  return programme ? programme.courses.filter((c) => c.live).length : 0;
}

/* ------------------------------------------------------------------ *
 * What a programme is CALLED in the picker, versus what it is called on a
 * certificate.
 *
 * Owner, 2026-08-04: "you don't have to say Bachelor of Accounting… there's too
 * much bachelor. And the level is already under the actual programme. So you
 * can just have the programme say Accounting. And likewise masters — you don't
 * have to say Master of Science, you can just say Science."
 *
 * 22 of the 41 programmes begin "Bachelor of", and the row already prints the
 * level on its second line, so the degree word was being said twice on every
 * row and was the first thing on all of them — which is the one position where
 * a word that never varies is worst, because it pushes the part that does vary
 * out to where the eye has to hunt for it.
 *
 * ONLY THE DEGREE WORDS COME OFF, not "Science in": stripping that too would
 * turn "Bachelor of Science in Accounting" into "Accounting" and collide it
 * with the real "Bachelor of Accounting", which is a different programme with a
 * different curriculum. What remains can still collide — BSc and MSc in
 * Accounting and Finance both reduce to "Science in Accounting and Finance" —
 * and that is fine and checked: the level line under them is exactly what tells
 * those two apart, which is why it is not optional on this row.
 * ------------------------------------------------------------------ */

const DEGREE_PREFIX = /^(?:bachelor|master|doctor)s?\s+of\s+/i;

/** The programme's name with the degree word taken off the front. */
export function programmeLabel(programme: Programme): string {
  return programme.name.replace(DEGREE_PREFIX, "").trim() || programme.name;
}

/** Sentence-cased level, for the line under it. The stored values are lowercase
 *  slugs from the scrape ("bachelors"), which is a fine key and a poor label. */
const LEVEL_LABELS: Record<string, string> = {
  bachelors: "Bachelor's",
  masters: "Master's",
  doctorate: "Doctorate",
  diploma: "Diploma",
};

export function levelLabel(programme: Programme): string | undefined {
  if (!programme.level) return undefined;
  return LEVEL_LABELS[programme.level] ?? programme.level;
}
