/* Turn the Streamline Freehand Duotone SVGs in public/icons into one inline
 * React module (src/icons.tsx).
 *
 * Inline rather than <Img src={staticFile(...)}> because these are DUOTONE: an
 * <img> can't be recoloured, and the video needs the two layers to carry brand
 * colours (and, in places, to animate independently). Same rule the platform
 * app follows — always inline SVG so icons respond to colour.
 *
 * Source set: "Freehand Duotone - Free" (streamlinehq.com), free tier.
 * Run: node scripts/build-icons.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(HERE, "..", "public", "icons");
const OUT = path.resolve(HERE, "..", "src", "icons.tsx");

/** The two colours Streamline ships duotone icons with. */
const LINE = /#020202/gi;
const DUO = /#0c6fff/gi;

const toPascal = (s) => s.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase());

const files = fs.readdirSync(SRC).filter((f) => f.endsWith(".svg"));
if (!files.length) {
  console.error(`No SVGs in ${SRC}`);
  process.exit(1);
}

const parts = [];
for (const file of files) {
  const raw = fs.readFileSync(path.join(SRC, file), "utf8");

  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 24 24";
  let body = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/<desc>[\s\S]*?<\/desc>/g, "")
    .replace(/fill-rule=/g, "fillRule=")
    .replace(/clip-rule=/g, "clipRule=")
    .replace(/stroke-width=/g, "strokeWidth=")
    .replace(/stroke-linecap=/g, "strokeLinecap=")
    .replace(/stroke-linejoin=/g, "strokeLinejoin=")
    .replace(LINE, "{line}")
    .replace(DUO, "{duo}")
    .trim();

  // fill="{line}" -> fill={line}
  body = body.replace(/"\{(line|duo)\}"/g, "{$1}");

  const name = toPascal(path.basename(file, ".svg"));
  parts.push(`export const ${name}: React.FC<IconProps> = ({
  size = 96,
  line = C.line,
  duo = C.duo,
  style,
}) => (
  <svg width={size} height={size} viewBox="${viewBox}" fill="none" style={style}>
    ${body.split("\n").join("\n    ")}
  </svg>
);`);
}

const out = `/* GENERATED by scripts/build-icons.mjs — do not edit by hand.
 * Source: public/icons/*.svg, Streamline "Freehand Duotone - Free".
 * Re-run the script after adding or replacing an SVG. */
import React from "react";

/** Default duotone pair, tuned to the reader app's surface. */
export const C = { line: "#171717", duo: "#c3cdea" } as const;

export type IconProps = {
  size?: number;
  /** the drawn line layer */
  line?: string;
  /** the flat fill behind it */
  duo?: string;
  style?: React.CSSProperties;
};

${parts.join("\n\n")}
`;

fs.writeFileSync(OUT, out);
console.log(`${files.length} icons -> ${path.relative(process.cwd(), OUT)}`);
