/* AUTO-GENERATED by scripts/gen-mingcute-icons.mjs — do not edit by hand.
 *
 * Mingcute Icons, resolved from the local @iconify-json/mingcute package at
 * generation time. Add a name to ICONS in the script and rerun
 * `npm run gen:mingcute`.
 *
 * A second set alongside MynaUI, kept deliberately small — see the script.
 */

import type { CSSProperties } from "react";

export type MingcuteIconName =
  | "down-small-line";

/* Path bodies only — a 24-grid viewBox is added by the component. Each keeps
 * stroke="currentColor", so an icon takes the colour of the text around it. */
const BODIES: Record<MingcuteIconName, string> = {
  "down-small-line":
    '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 11L12 13.828L9.172 11"/>',
};

/**
 * One icon, inlined as SVG. Safe in server and client components alike: no set
 * is imported at runtime, only the bodies above.
 *
 * `strokeWidth` overrides Mingcute's 2 — which is a third heavier than
 * MynaUI's 1.5, so an icon sat beside MynaUI glyphs usually wants it nudged
 * down to match.
 */
export function MingcuteIcon({
  name,
  size = 20,
  className,
  style,
  strokeWidth,
}: {
  name: MingcuteIconName;
  size?: number;
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
}) {
  const body = strokeWidth
    ? BODIES[name].replace(/stroke-width="[^"]*"/g, `stroke-width="${strokeWidth}"`)
    : BODIES[name];

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
