/* AUTO-GENERATED by scripts/gen-ultimate-icons.mjs — do not edit by hand.
 *
 * Streamline · Ultimate Colors (Free), resolved from the local
 * @iconify-json/streamline-ultimate-color package at generation time. Add a name
 * to ICONS in the script and rerun `npm run gen:ultimate`.
 *
 * CC BY 4.0 — attribution is owed, alongside the MynaUI, Streamline Plump and
 * Kameleon credits. The same family is hand-inlined in reader/file-icons.tsx;
 * this module is the reproducible route to it.
 *
 * MULTICOLOUR ON PURPOSE. These ignore `currentColor`: each carries its own
 * fills plus #191919 line work, because on the feedback row the colour is what
 * separates a reaction from its neighbours at 20px.
 *
 * TWO BODIES PER ICON. `full` is the icon as drawn; `rest` is the same icon
 * with every coloured fill swapped for a warm neutral and the line work left
 * alone. That is how an unchosen mark goes QUIET without going FAINT — see the
 * long note in the generator, and a793eae for the CSS filter that failed.
 */

import type { CSSProperties } from "react";

export type UltimateIconName =
  | "flag"
  | "smiley-happy"
  | "smiley-disapointed"
  | "smiley-sad-1"
  | "check"
  | "question-help-message"
  | "time-clock-circle"
  | "task-list-text-1"
  | "delete-2";

const BODIES: Record<UltimateIconName, { full: string; rest: string }> = {
  "flag": {
    full:
      '<g fill="none"><path fill="#ff808c" d="M11.045 4.826h9.565c.526 0 .62.269.21.598l-6.428 5.141l7.174 5.74H7.792a.478.478 0 0 1-.443-.659c.663-1.643 3.696-2.211 3.696-2.211z"/><path fill="#ffbfc5" d="M11.044 13.435H4.35V1.957h5.739a.956.956 0 0 1 .956.956z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M4.349 1.957h5.739a.956.956 0 0 1 .956.956v1.913h9.566c.526 0 .62.269.209.598l-6.427 5.141l7.174 5.74H7.792a.478.478 0 0 1-.444-.659c.664-1.643 3.696-2.211 3.696-2.211H4.35m6.693-8.609v8.609M2.435 1v22"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M11.045 4.826h9.565c.526 0 .62.269.21.598l-6.428 5.141l7.174 5.74H7.792a.478.478 0 0 1-.443-.659c.663-1.643 3.696-2.211 3.696-2.211z"/><path fill="#ededea" d="M11.044 13.435H4.35V1.957h5.739a.956.956 0 0 1 .956.956z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M4.349 1.957h5.739a.956.956 0 0 1 .956.956v1.913h9.566c.526 0 .62.269.209.598l-6.427 5.141l7.174 5.74H7.792a.478.478 0 0 1-.444-.659c.664-1.643 3.696-2.211 3.696-2.211H4.35m6.693-8.609v8.609M2.435 1v22"/></g>',
  },
  "smiley-happy": {
    full:
      '<g fill="none"><path fill="#ffef5e" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path fill="#fff9bf" d="M12 4.826a11.8 11.8 0 0 1 10.994 7.517c0-.114.006-.228.006-.343a11 11 0 1 0-21.994.343A11.8 11.8 0 0 1 12 4.826"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path stroke="#191919" d="M6.739 10.326a.24.24 0 0 1 0-.478m.001.478a.24.24 0 0 0 0-.478m10.52.478a.24.24 0 0 1 0-.478m0 .478a.24.24 0 0 0 0-.478"/><path fill="#ff808c" stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M15.705 15.348a.957.957 0 0 1 .927 1.194a4.782 4.782 0 0 1-9.264 0a.956.956 0 0 1 .927-1.194z"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path fill="#ededea" d="M12 4.826a11.8 11.8 0 0 1 10.994 7.517c0-.114.006-.228.006-.343a11 11 0 1 0-21.994.343A11.8 11.8 0 0 1 12 4.826"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path stroke="#191919" d="M6.739 10.326a.24.24 0 0 1 0-.478m.001.478a.24.24 0 0 0 0-.478m10.52.478a.24.24 0 0 1 0-.478m0 .478a.24.24 0 0 0 0-.478"/><path fill="#ededea" stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M15.705 15.348a.957.957 0 0 1 .927 1.194a4.782 4.782 0 0 1-9.264 0a.956.956 0 0 1 .927-1.194z"/></g>',
  },
  "smiley-disapointed": {
    full:
      '<g fill="none"><path fill="#ffef5e" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path fill="#fff9bf" d="M12 4.826a11.8 11.8 0 0 1 10.994 7.517c0-.114.006-.228.006-.343a11 11 0 1 0-21.994.343A11.8 11.8 0 0 1 12 4.826"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M9.608 18.217h4.783M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M14.393 12.375a2.257 2.257 0 0 0 3.826 0m-8.609 0a2.257 2.257 0 0 1-3.826 0m-.957-2.766l3.826-1.913m10.521 1.913l-3.826-1.913"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path fill="#ededea" d="M12 4.826a11.8 11.8 0 0 1 10.994 7.517c0-.114.006-.228.006-.343a11 11 0 1 0-21.994.343A11.8 11.8 0 0 1 12 4.826"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M9.608 18.217h4.783M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M14.393 12.375a2.257 2.257 0 0 0 3.826 0m-8.609 0a2.257 2.257 0 0 1-3.826 0m-.957-2.766l3.826-1.913m10.521 1.913l-3.826-1.913"/></g>',
  },
  "smiley-sad-1": {
    full:
      '<g fill="none"><path fill="#ffef5e" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path fill="#fff9bf" d="M12 4.826a11.8 11.8 0 0 1 10.994 7.517c0-.114.006-.228.006-.343a11 11 0 1 0-21.994.343A11.8 11.8 0 0 1 12 4.826"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M7.696 18.696a4.304 4.304 0 1 1 8.609 0"/><path stroke="#191919" d="M6.74 10.326a.24.24 0 0 1 0-.478m0 .478a.24.24 0 0 0 0-.478m10.522.478a.24.24 0 0 1 0-.478m0 .478a.24.24 0 0 0 0-.478"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path fill="#ededea" d="M12 4.826a11.8 11.8 0 0 1 10.994 7.517c0-.114.006-.228.006-.343a11 11 0 1 0-21.994.343A11.8 11.8 0 0 1 12 4.826"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 23c6.075 0 11-4.925 11-11S18.075 1 12 1S1 5.925 1 12s4.925 11 11 11"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M7.696 18.696a4.304 4.304 0 1 1 8.609 0"/><path stroke="#191919" d="M6.74 10.326a.24.24 0 0 1 0-.478m0 .478a.24.24 0 0 0 0-.478m10.522.478a.24.24 0 0 1 0-.478m0 .478a.24.24 0 0 0 0-.478"/></g>',
  },
  "check": {
    full:
      '<g fill="none"><path fill="#78eb7b" d="M1.987 13.704a1.084 1.084 0 0 0 0 1.534l5.203 5.204c.424.423 1.11.423 1.534 0l13.289-13.29a1.084 1.084 0 0 0 0-1.533l-2.06-2.06a1.084 1.084 0 0 0-1.533 0L7.957 14.022L5.58 11.644a1.085 1.085 0 0 0-1.534 0z"/><path fill="#c9f7ca" d="M7.957 17.167L20.76 4.365l-.809-.809a1.085 1.085 0 0 0-1.534 0L7.957 14.022L5.58 11.644a1.084 1.084 0 0 0-1.534 0l-.809.809z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M1.987 13.704a1.084 1.084 0 0 0 0 1.534l5.203 5.204c.424.423 1.11.423 1.534 0l13.289-13.29a1.084 1.084 0 0 0 0-1.533l-2.06-2.06a1.084 1.084 0 0 0-1.533 0L7.957 14.022L5.58 11.644a1.085 1.085 0 0 0-1.534 0z"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M1.987 13.704a1.084 1.084 0 0 0 0 1.534l5.203 5.204c.424.423 1.11.423 1.534 0l13.289-13.29a1.084 1.084 0 0 0 0-1.533l-2.06-2.06a1.084 1.084 0 0 0-1.533 0L7.957 14.022L5.58 11.644a1.085 1.085 0 0 0-1.534 0z"/><path fill="#ededea" d="M7.957 17.167L20.76 4.365l-.809-.809a1.085 1.085 0 0 0-1.534 0L7.957 14.022L5.58 11.644a1.084 1.084 0 0 0-1.534 0l-.809.809z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M1.987 13.704a1.084 1.084 0 0 0 0 1.534l5.203 5.204c.424.423 1.11.423 1.534 0l13.289-13.29a1.084 1.084 0 0 0 0-1.533l-2.06-2.06a1.084 1.084 0 0 0-1.533 0L7.957 14.022L5.58 11.644a1.085 1.085 0 0 0-1.534 0z"/></g>',
  },
  "question-help-message": {
    full:
      '<g fill="none"><path fill="#66e1ff" d="M22.044 19.288H6.26l-4.878 3.55A.24.24 0 0 1 1 22.647V2.07a.957.957 0 0 1 .957-.956h20.087A.956.956 0 0 1 23 2.07v16.261a.957.957 0 0 1-.956.957"/><path fill="#c2f3ff" d="m1.383 22.838l4.878-3.55h.118L23 2.668V2.07a.956.956 0 0 0-.957-.956H1.957A.957.957 0 0 0 1 2.07v20.575a.24.24 0 0 0 .383.193"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M8.651 8.05a3.589 3.589 0 1 1 4.364 3.502a.96.96 0 0 0-.777.933v1.064"/><path stroke="#191919" d="M12.24 16.418a.24.24 0 0 1 0-.478m.001.478a.24.24 0 0 0 0-.478"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M22.044 19.288H6.26l-4.878 3.55A.24.24 0 0 1 1 22.647V2.07a.957.957 0 0 1 .957-.956h20.087A.956.956 0 0 1 23 2.07v16.261a.957.957 0 0 1-.956.957"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M22.044 19.288H6.26l-4.878 3.55A.24.24 0 0 1 1 22.647V2.07a.957.957 0 0 1 .957-.956h20.087A.956.956 0 0 1 23 2.07v16.261a.957.957 0 0 1-.956.957"/><path fill="#ededea" d="m1.383 22.838l4.878-3.55h.118L23 2.668V2.07a.956.956 0 0 0-.957-.956H1.957A.957.957 0 0 0 1 2.07v20.575a.24.24 0 0 0 .383.193"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M8.651 8.05a3.589 3.589 0 1 1 4.364 3.502a.96.96 0 0 0-.777.933v1.064"/><path stroke="#191919" d="M12.24 16.418a.24.24 0 0 1 0-.478m.001.478a.24.24 0 0 0 0-.478"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M22.044 19.288H6.26l-4.878 3.55A.24.24 0 0 1 1 22.647V2.07a.957.957 0 0 1 .957-.956h20.087A.956.956 0 0 1 23 2.07v16.261a.957.957 0 0 1-.956.957"/></g>',
  },
  "time-clock-circle": {
    full:
      '<g fill="none"><path fill="#66e1ff" d="M12 22.543c5.821 0 10.54-4.72 10.54-10.542S17.822 1.459 12 1.459c-5.823 0-10.542 4.72-10.542 10.542s4.72 10.542 10.541 10.542"/><path fill="#c2f3ff" d="M4.545 19.455A10.542 10.542 0 0 1 19.453 4.547z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 22.543c5.821 0 10.54-4.72 10.54-10.542S17.822 1.459 12 1.459c-5.823 0-10.542 4.72-10.542 10.542s4.72 10.542 10.541 10.542"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 6.96V12l5.5 5.043"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M12 22.543c5.821 0 10.54-4.72 10.54-10.542S17.822 1.459 12 1.459c-5.823 0-10.542 4.72-10.542 10.542s4.72 10.542 10.541 10.542"/><path fill="#ededea" d="M4.545 19.455A10.542 10.542 0 0 1 19.453 4.547z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 22.543c5.821 0 10.54-4.72 10.54-10.542S17.822 1.459 12 1.459c-5.823 0-10.542 4.72-10.542 10.542s4.72 10.542 10.541 10.542"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 6.96V12l5.5 5.043"/></g>',
  },
  "task-list-text-1": {
    full:
      '<g fill="none"><path fill="#c77f67" stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M20.133 2.907H14.92a3.186 3.186 0 0 0-5.836 0H3.867a.957.957 0 0 0-.956.957v18.18a.957.957 0 0 0 .956.956h16.266a.957.957 0 0 0 .957-.957V3.864a.957.957 0 0 0-.957-.957"/><path fill="#e3e3e3" d="M17.758 17.317c.297-.347.46-.788.462-1.244V5.778H5.78V20.13h8.688a1.91 1.91 0 0 0 1.453-.67z"/><path fill="#fff" d="M5.781 18.204L18.21 5.774H5.781z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M15.349 8.648H8.65m6.699 3.827H8.65m4.307 3.827H8.65m9.108 1.015c.297-.347.46-.788.462-1.244V5.778H5.78V20.13h8.688a1.91 1.91 0 0 0 1.453-.67z"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M20.133 2.907H14.92a3.186 3.186 0 0 0-5.836 0H3.867a.957.957 0 0 0-.956.957v18.18a.957.957 0 0 0 .956.956h16.266a.957.957 0 0 0 .957-.957V3.864a.957.957 0 0 0-.957-.957"/><path fill="#ededea" d="M17.758 17.317c.297-.347.46-.788.462-1.244V5.778H5.78V20.13h8.688a1.91 1.91 0 0 0 1.453-.67z"/><path fill="#ededea" d="M5.781 18.204L18.21 5.774H5.781z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M15.349 8.648H8.65m6.699 3.827H8.65m4.307 3.827H8.65m9.108 1.015c.297-.347.46-.788.462-1.244V5.778H5.78V20.13h8.688a1.91 1.91 0 0 0 1.453-.67z"/></g>',
  },
  "delete-2": {
    full:
      '<g fill="none"><path fill="#ff808c" d="M12 22.542c5.822 0 10.542-4.72 10.542-10.542S17.822 1.458 12 1.458S1.458 6.178 1.458 12S6.178 22.542 12 22.542"/><path fill="#ffbfc5" d="M4.546 19.454A10.542 10.542 0 0 1 19.454 4.546z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 22.542c5.822 0 10.542-4.72 10.542-10.542S17.822 1.458 12 1.458S1.458 6.178 1.458 12S6.178 22.542 12 22.542M7.417 7.417l9.166 9.166m0-9.166l-9.166 9.166"/></g>',
    rest:
      '<g fill="none"><path fill="#ededea" d="M12 22.542c5.822 0 10.542-4.72 10.542-10.542S17.822 1.458 12 1.458S1.458 6.178 1.458 12S6.178 22.542 12 22.542"/><path fill="#ededea" d="M4.546 19.454A10.542 10.542 0 0 1 19.454 4.546z"/><path stroke="#191919" stroke-linecap="round" stroke-linejoin="round" d="M12 22.542c5.822 0 10.542-4.72 10.542-10.542S17.822 1.458 12 1.458S1.458 6.178 1.458 12S6.178 22.542 12 22.542M7.417 7.417l9.166 9.166m0-9.166l-9.166 9.166"/></g>',
  },
};

/**
 * One Ultimate Colors icon, inlined as SVG. Safe in server and client
 * components alike: no set is imported at runtime, only the bodies above.
 *
 * `muted` draws the rest state — full line work, no colour.
 */
export function UltimateIcon({
  name,
  size = 20,
  muted = false,
  className,
  style,
}: {
  name: UltimateIconName;
  size?: number;
  muted?: boolean;
  className?: string;
  style?: CSSProperties;
}) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
      dangerouslySetInnerHTML={{ __html: muted ? BODIES[name].rest : BODIES[name].full }}
    />
  );
}
