/* Pixel objects — the drawings, as data. One char per pixel; `.` is clear.
 *
 * Kept free of React so two things can read it: the video (pixels.tsx renders
 * these as crisp SVG) and scripts/export-pixels.mjs, which writes every object
 * out as its own SVG + PNG in public/assets/pixel/ for use anywhere else
 * (owner, 2026-10-09: "create separate different assets"). All original
 * drawings — nothing to license. Rows shorter than the widest are padded. */

export type Art = { rows: string[]; pal: Record<string, string> };

const OUT = "#1E1A16";

export const ICONS: Record<string, Art> = {
  coin: {
    pal: { o: "#3B2600", y: "#F2C230", Y: "#FFF0A0", d: "#C08A10", k: "#6B4300" },
    rows: [
      ".....oooooo.....",
      "...ooyyyyyyoo...",
      "..oyYYyyyyyyyo..",
      ".oyYyyyyyyyyydo.",
      ".oYyykkyyykkydo.",
      "oyYyykkyykkyyydo",
      "oyYyykkykkyyyydo",
      "oyyyykkkkyyyyydo",
      "oyyyykkkkyyyyydo",
      "oyyyykkykkyyyydo",
      "oyyyykkyykkyyydo",
      ".oyyykkyyykkydo.",
      ".oyyyyyyyyyyddo.",
      "..oyyyyyyyyddo..",
      "...ooddddddoo...",
      ".....oooooo.....",
    ],
  },
  note: {
    pal: { o: "#1D3B1A", G: "#3F8A35", g: "#62B04F", l: "#A8DD8C", w: "#E4F3D6", k: "#1D3B1A" },
    rows: [
      "oooooooooooooooooooooo",
      "oGGGGGGGGGGGGGGGGGGGGo",
      "oGllgggggwwwwgggggllGo",
      "oGlgggggwwwwwwgggggglGo".slice(0, 22),
      "oGgggggwwkkwwwwggggggGo".slice(0, 22),
      "oGgkkggwwkwkwwwggkkggGo".slice(0, 22),
      "oGgkkggwwkkwwwwggkkggGo".slice(0, 22),
      "oGgggggwwkwkwwwggggggGo".slice(0, 22),
      "oGlgggggwwwwwwgggggglGo".slice(0, 22),
      "oGllgggggwwwwgggggllGo",
      "oGGGGGGGGGGGGGGGGGGGGo",
      "oooooooooooooooooooooo",
    ],
  },
  calculator: {
    pal: { o: OUT, d: "#3A3A40", s: "#B9E3A8", K: "#22401C", w: "#ECEAE4", r: "#D7261E" },
    rows: [
      "oooooooooooo",
      "oddddddddddo",
      "odssssssssdo",
      "odsKKsKKsKdo",
      "odssssssssdo",
      "oddddddddddo",
      "odwwdwwdrrdo",
      "odwwdwwdrrdo",
      "oddddddddddo",
      "odwwdwwdwwdo",
      "odwwdwwdwwdo",
      "oddddddddddo",
      "odwwdwwdwwdo",
      "odwwdwwdwwdo",
      "oddddddddddo",
      "oooooooooooo",
    ],
  },
  hourglass: {
    pal: { o: OUT, b: "#8A5A2B", B: "#B57A3C", c: "#DDEFF7", s: "#F2C230" },
    rows: [
      "oooooooooooo",
      "oBBBBBBBBBBo",
      "oooooooooooo",
      ".occccccccco",
      ".ocssssssco.",
      "..ocssssco..",
      "...ocsscо...".replace("о", "o"),
      "....occo....",
      "....ocso....",
      "...occsco...",
      "..occcssco..",
      ".occcsssscо.".replace("о", "o"),
      ".ocsssssssco",
      "oooooooooooo",
      "obbbbbbbbbbo",
      "oooooooooooo",
    ],
  },
  bank: {
    pal: { o: OUT, w: "#EFE9DC", g: "#C9C1AD", r: "#D7261E" },
    rows: [
      ".......oo.......",
      ".....oowwoo.....",
      "...oowwrrwwoo...",
      ".oowwwwwwwwwwoo.",
      "oooooooooooooooo",
      "owwwwwwwwwwwwwwo",
      "oooooooooooooooo",
      ".owg.owg.owg.owg",
      ".owg.owg.owg.owg",
      ".owg.owg.owg.owg",
      ".owg.owg.owg.owg",
      ".owg.owg.owg.owg",
      "oooooooooooooooo",
      "owwwwwwwwwwwwwwo",
      "oooooooooooooooo",
    ],
  },
  chart: {
    pal: { o: OUT, w: "#F6F4EE", b: "#2A2826", r: "#D7261E", l: "#CFCAC0" },
    rows: [
      "oooooooooooooooo",
      "owwwwwwwwwwwwwwo",
      "owwwwwwwwwwrrrwo",
      "owwwwwwwwwwwrrwo",
      "owwwwwwwwwwrwrwo",
      "owwwwwwwwwrwwwwo",
      "owwwwwwwbrwwbbwo",
      "owwwwwwrbwwwbbwo",
      "owwwbbrwbwbbbbwo",
      "owwrbbwwbwbbbbwo",
      "owbbbbwwbwbbbbwo",
      "owbbbbwbbwbbbbwo",
      "owlllllllllllllo",
      "oooooooooooooooo",
    ],
  },
  bond: {
    pal: { o: OUT, p: "#F3EAD2", l: "#B9A985", r: "#D7261E", R: "#9E1712" },
    rows: [
      "oooooooooooooooo",
      "oppppppppppppppo",
      "opllllllllllllpo",
      "oppppppppppppppo",
      "opllllllllpppppo",
      "oppppppppppppppo",
      "opllllllppppppo",
      "oppppppppprrrrpo",
      "oplllllppprRRrpo",
      "oppppppppprRRrpo",
      "oppppppppprrrrpo",
      "oppppppppppRpRpo",
      "oooooooooooooooo",
    ],
  },

  /* ---- added 2026-10-09: the student-finance world, as separate assets ---- */
  book: {
    pal: { o: OUT, R: "#9E1712", r: "#D7261E", g: "#F2C230", p: "#F3EAD2", l: "#CFC4A8" },
    rows: [
      "ooooooooooooooo.",
      "oRRRRRRRRRRRRRo.",
      "oRrrrrrrrrrrrRo.",
      "oRrrggggggrrrRo.",
      "oRrrrrrrrrrrrRo.",
      "oRrrggggggrrrRo.",
      "oRrrrrrrrrrrrRo.",
      "oRrrrrrrrrrrrRo.",
      "oRrrrrrrrrrrrRo.",
      "oRRRRRRRRRRRRRoo",
      "opppppppppppppo.",
      "opllllllllllllo.",
      "oooooooooooooooo",
    ],
  },
  gradcap: {
    pal: { o: OUT, k: "#2A2826", K: "#3F3B37", t: "#F2C230" },
    rows: [
      ".......oo.......",
      ".....ookkoo.....",
      "...ookkkkkkoo...",
      ".ookkkkkkkkkkoo.",
      "okkkkkkkkkkkkkko",
      ".ookkkkkkkkkkoot",
      "...ookkkkkkoo..t",
      "....oKKKKKKo...t",
      "....oKKKKKKo..tt",
      "....oKKKKKKo..tt",
      ".....oooooo.....",
    ],
  },
  phone: {
    pal: { o: OUT, d: "#2A2826", s: "#9FD3F0", S: "#DDF1FB", b: "#6E6A64" },
    rows: [
      "oooooooooo",
      "oddddddddo",
      "odSSssssdo",
      "odSsssssdo",
      "odssssssdo",
      "odssssssdo",
      "odssssssdo",
      "odssssssdo",
      "odssssssdo",
      "odssssssdo",
      "odssssssdo",
      "oddddddddo",
      "odddbbdddo",
      "oddddddddo",
      "oooooooooo",
    ],
  },
  clock: {
    pal: { o: OUT, w: "#F6F4EE", h: "#131211", r: "#D7261E" },
    rows: [
      ".....oooooo.....",
      "...oowwwwwwoo...",
      "..owwwwrwwwwwo..",
      ".owwwwwwhwwwwwo.",
      ".owwwwwwhwwwwwo.",
      "owwwwwwwhwwwwwwo",
      "owwwwwwwhwwwwwwo",
      "orwwwwwwhhhhwwro",
      "owwwwwwwwwwwwwwo",
      "owwwwwwwwwwwwwwo",
      ".owwwwwwwwwwwwo.",
      ".owwwwwwwwwwwwo.",
      "..owwwwwrwwwwo..",
      "...oowwwwwwoo...",
      ".....oooooo.....",
    ],
  },
  wallet: {
    pal: { o: OUT, b: "#8A5A2B", B: "#5E3B1A", c: "#F2C230", C: "#C08A10", g: "#62B04F" },
    rows: [
      "...gggggggg.....",
      ".oooooooooooooo.",
      "oBBBBBBBBBBBBBBo",
      "oooooooooooooooo",
      "obbbbbbbbbbbbbbo",
      "obbbbbbbbbbooooo",
      "obbbbbbbbbboccco",
      "obbbbbbbbbbocCco",
      "obbbbbbbbbboccco",
      "obbbbbbbbbbooooo",
      "obbbbbbbbbbbbbbo",
      "oBBBBBBBBBBBBBBo",
      "oooooooooooooooo",
    ],
  },
  bulb: {
    pal: { o: OUT, y: "#FFE680", Y: "#F2C230", w: "#FFFFFF", g: "#A8A49C", G: "#6E6A64" },
    rows: [
      "...oooooo...",
      "..oyyyyyyo..",
      ".oywwyyyyyo.",
      "oywyyyyyyyyo",
      "oyyyyyyyyyyo",
      "oyyyyyyyyyyo",
      "oyyyyYYyyyyo",
      ".oyyyYYyyyo.",
      "..oyyYYyyo..",
      "...oyYYyo...",
      "...oggggo...",
      "...oGGGGo...",
      "...oggggo...",
      "....oGGo....",
      ".....oo.....",
    ],
  },
  receipt: {
    pal: { o: OUT, p: "#F6F4EE", l: "#B9A985", k: "#131211", r: "#D7261E" },
    rows: [
      "oooooooooooo",
      "oppppppppppo",
      "opllllllpppo",
      "oppppppppppo",
      "opllllplllpo",
      "oppppppppppo",
      "opllllllpppo",
      "oppppppppppo",
      "opkkkkkkkkpo",
      "oppppppppppo",
      "oppppprrrrpo",
      "oppppppppppo",
      "opoppoppoppo",
      "o.oo.oo.oo.o",
    ],
  },
  piggy: {
    pal: { o: OUT, p: "#F29AAE", P: "#D0607A", s: "#131211", w: "#FFD6DF", c: "#F2C230" },
    rows: [
      ".......cc.........",
      "......occo........",
      "....ooossooo......",
      "..oopppppppppoo...",
      ".opwwppppppppppo..",
      "opwpppppppppppppo.",
      "oppsppppppppppppPo",
      "oppppppppppppppPPo",
      "PPppppppppppppppPo",
      "PPppppppppppppppo.",
      ".opppppppppppppo..",
      "..oPPoooooooPPo...",
      "..oPPo.....oPPo...",
      "..oooo.....oooo...",
    ],
  },
};
