"use client";

import { useEffect, useState } from "react";

/* Booklesss is a phone app. This is what a desktop visitor gets instead.
 *
 * The reader is built to be installed to a home screen and read on the way to
 * class — that's the product, and a laptop isn't where it happens. Rather than
 * maintain a desktop experience nobody uses, wide viewports get pointed at
 * their phone.
 *
 * There is a way past it, deliberately. A hard block would be wrong twice
 * over: the owner writes and checks content on a desktop, and a student on a
 * campus lab machine with no phone to hand is still a student who wants to
 * read. So the escape is a plain link, it's remembered, and it doesn't nag
 * again on that machine.
 *
 * Only the width is tested, not the user agent. UA sniffing is a losing game —
 * tablets, desktop-mode browsers and Windows touch laptops all lie — and the
 * honest question here is "is this a small screen being held in a hand",
 * which is what the media query answers. An installed PWA is let through on
 * any size: if they took the trouble to install it, they've understood the
 * pitch. */

const PASSED = "booklesss-desktop-pass";
const MOBILE_MAX = 1024;

export function DesktopGate() {
  const [show, setShow] = useState(false);

  useEffect(() => {
    if (localStorage.getItem(PASSED) === "1") return;

    const installed =
      window.matchMedia("(display-mode: standalone)").matches ||
      (navigator as Navigator & { standalone?: boolean }).standalone === true;
    if (installed) return;

    const mq = window.matchMedia(`(min-width: ${MOBILE_MAX + 1}px)`);
    const apply = () => setShow(mq.matches);
    apply();
    // Someone resizing a window down to phone width should be let straight in.
    mq.addEventListener("change", apply);
    return () => mq.removeEventListener("change", apply);
  }, []);

  if (!show) return null;

  const pass = () => {
    localStorage.setItem(PASSED, "1");
    setShow(false);
  };

  return (
    <div className="desktop-gate">
      <div className="desktop-gate-card">
        <p className="desktop-gate-kicker">Bklsss</p>
        <h1 className="desktop-gate-title">Made for your phone</h1>
        <p className="desktop-gate-body">
          Your notes live in your pocket — installed to your home screen, and readable with no
          connection. Scan this to open it on your phone, then add it to your home screen.
        </p>

        {/* Static file, generated by scripts/gen-qr.mjs — no QR library reaches
            the browser, and phones never download any of this. */}
        <img
          src="/install-qr.svg"
          alt="QR code linking to booklesss.vercel.app"
          className="desktop-gate-qr"
          width={188}
          height={188}
        />

        <p className="desktop-gate-url">booklesss.vercel.app</p>

        <button type="button" onClick={pass} className="desktop-gate-pass">
          Continue on this computer
        </button>
      </div>
    </div>
  );
}
