-- Step content moves from static HTML files into the database (BUILD_PLAN §2).
-- Authoring stays in the repo's Python pipeline; generate_step.py publishes
-- body HTML + metadata here. The Next.js app renders rows at /steps/[slug].
-- Applied to the live project 2026-07-15 via MCP (migration: steps_content_table).

create table public.steps (
  slug         text primary key check (slug ~ '^[a-z0-9-]{1,64}$'),
  course_code  text not null check (course_code ~ '^[a-z]{2,4}$'),  -- tm, sm, cf, bba, ops
  lesson       int,
  step_label   text,                    -- "Step 2.1"
  title        text not null,
  description  text,
  body_html    text not null,           -- generated by the Python pipeline
  outcomes     jsonb not null default '[]',
  added_value  jsonb not null default '[]',
  access       text not null default 'members'
               check (access in ('public','members','internal')),
  status       text not null default 'draft'
               check (status in ('draft','published','archived')),
  version      int not null default 1,
  published_at timestamptz,
  updated_at   timestamptz not null default now()
);

alter table public.steps enable row level security;

-- Published public rows readable by anyone (lead-magnet steps).
create policy "read published public" on public.steps for select
  using (status = 'published' and access = 'public');

-- Published members/internal rows readable by any signed-in user; plan and
-- owner-role enforcement happens at the app route (canReadStep), RLS is the
-- backstop that keeps drafts and signed-out readers away.
create policy "read published members" on public.steps for select to authenticated
  using (status = 'published' and access in ('members','internal'));

-- Writes via service role / MCP only: no insert/update policies.

create index steps_course_idx on public.steps (course_code, lesson, step_label);

-- Per-step client data (tap-define glossary, brand favicons, per-step JS)
-- and index-display fields (applied live as steps_client_data_columns).
alter table public.steps
  add column course_chip text,
  add column eyebrow     text,
  add column minutes     int,
  add column glossary    jsonb not null default '{}',
  add column brand       jsonb not null default '{}',
  add column extra_js    text;
