// Regenerates src/components/identity/avatars.tsx from
// @iconify-json/streamline-kameleon-color.
//   npm run gen:avatars
//
// The twelve profile pictures a student picks from on first visit. There is no
// upload — these are the whole set, so they have to read as twelve different
// people at 32px.
//
// Kameleon draws each icon as a finished badge: a full-bleed 48px disc in one
// of the set's four flat colours with the subject sitting on it. So unlike the
// Plump avatars this replaced, nothing is recoloured here — the disc IS the
// avatar, and the table below only picks which twelve and in what order.
//
// Four disc colours across twelve avatars means each colour comes up three
// times, so the order alternates them: at six columns the picker reads as a
// checkerboard rather than four bands of one hue, and no two neighbours are
// the same colour.
//
// Same generation trick as gen-icons.mjs: only the twelve chosen icons are
// inlined, because the set is 400 icons and this renders in a client
// component.
import { getIconData, iconToSVG } from "@iconify/utils";
import kameleon from "@iconify-json/streamline-kameleon-color/icons.json" with { type: "json" };
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/* id · icon · label
 *
 * `label` is what a screen reader says and what the picker's tooltip shows, so
 * it names the thing, not the colour. */
const AVATARS = [
  ["astronaut", "astronaut", "Astronaut"], //      cyan
  ["robot", "robot", "Robot"], //                  teal
  ["smiley", "love-smiley", "Smiling face"], //    red
  ["peace", "peace", "Peace sign"], //             amber
  ["ladybug", "ladybug", "Ladybird"], //           cyan
  ["butterfly", "butterfly", "Butterfly"], //      teal
  ["ufo", "ufo", "Flying saucer"], //              red
  ["party", "party-poppers", "Party popper"], //   amber
  ["rainbow", "rainbow", "Rainbow"], //            cyan
  ["strawberry", "strawberry", "Strawberry"], //   teal
  ["dice", "dices", "Dice"], //                    red
  ["skate", "skate", "Ice skate"], //              amber
];

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "components", "identity", "avatars.tsx");

const rows = AVATARS.map(([id, icon, label]) => {
  const data = getIconData(kameleon, icon);
  if (!data) throw new Error(`Unknown Kameleon icon: "${icon}"`);
  const body = iconToSVG(data, { height: 48, width: 48 }).body;
  return { id, label, body };
});

const union = rows.map((r) => `  | "${r.id}"`).join("\n");
const entries = rows
  .map(
    (r) =>
      `  {\n    id: "${r.id}",\n    label: "${r.label}",\n    body:\n      '${r.body.replace(/'/g, "\\'")}',\n  },`,
  )
  .join("\n");

writeFileSync(
  OUT,
  `/* AUTO-GENERATED by scripts/gen-avatars.mjs — do not edit by hand.
 *
 * Streamline "Kameleon Colors" free set (CC BY 4.0, attribution owed — as with
 * the composer's file-type badges and the dashboard's stat marks). Each icon is
 * a complete circular badge, drawn in the set's own colours: a full-bleed disc
 * plus its subject. Nothing here is recoloured.
 *
 * Add or swap an avatar in the script's AVATARS table and rerun
 * \`npm run gen:avatars\`.
 */
"use client";

export type AvatarId =
${union};

type Entry = {
  id: AvatarId;
  label: string;
  body: string;
};

/** The whole picker, in the order it is drawn. */
export const AVATARS: Entry[] = [
${entries}
];

const BY_ID = new Map(AVATARS.map((a) => [a.id, a]));

/** The one a student gets before they have chosen. */
export const DEFAULT_AVATAR: AvatarId = "${rows[0].id}";

/** An id this build still draws. A stored id can outlive its entry — the set
 *  was Plump before it was Kameleon — so anything unknown resolves to the
 *  default rather than leaving a picker with nothing selected. */
export function resolveAvatar(id: AvatarId | string | null | undefined): AvatarId {
  return BY_ID.has(id as AvatarId) ? (id as AvatarId) : DEFAULT_AVATAR;
}

/**
 * One avatar, inlined as SVG. The art is a full-bleed disc, so it needs no
 * shell of its own — anything round it is the caller's border, not the icon's.
 */
export function Avatar({ id, size = 40 }: { id: AvatarId | string; size?: number }) {
  const a = BY_ID.get(resolveAvatar(id))!;

  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 48 48"
      fill="none"
      role="img"
      aria-label={a.label}
      className="shrink-0"
      dangerouslySetInnerHTML={{ __html: a.body }}
    />
  );
}

/** The label for an id — for alt text and tooltips outside the picker. */
export function avatarLabel(id: AvatarId | string): string {
  return BY_ID.get(resolveAvatar(id))!.label;
}
`,
  "utf8",
);

console.log(`Wrote ${rows.length} avatars to ${OUT}`);
