// Regenerates src/components/icons/myna.tsx from @iconify-json/mynaui.
//   npm run gen:icons
//
// Why generate instead of importing the set: the whole MynaUI JSON is ~2,650
// icons, and half the app's icons sit in client components ("use client"), where
// importing it would ship the entire set to the browser. The names ICONS lists
// below are resolved here, at author time, and only their path bodies land in
// the generated module — which then works in server and client components
// alike. Adding an icon is one line here plus a rerun.
import { getIconData, iconToSVG } from "@iconify/utils";
import mynaui from "@iconify-json/mynaui/icons.json" with { type: "json" };
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/* Every icon the UI draws, grouped by where it's used so an unused one is
 * obvious. `-solid` is MynaUI's filled variant, which the sidebars use to mark
 * the current row — line at rest, solid when active. */
const ICONS = [
  // chrome: header, search, drawers, rails
  "search",
  "question-circle",
  "info-circle",
  "zap",
  "menu",
  "sidebar",
  "chevron-down",
  "chevron-right",
  // home rail destinations
  "layout-dashboard",
  "layout-dashboard-solid",
  "book-open",
  "book-open-solid",
  "clipboard",
  "clipboard-solid",
  "calendar",
  "calendar-solid",
  "cog",
  "cog-solid",
  // the end-of-section answer, and progress + the dashboard's stat tiles
  "check",
  "check-circle-solid",
  "question-circle-solid",
  "x-circle",
  "x-circle-solid",
  "chart-bar-increasing",
  "check-circle",
  "clock-1",
  "target",
  // the parked /old-home scratch rail
  "users",
  "puzzle",
  "chart-bar",
  "credit-card",
];

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "components", "icons", "myna.tsx");

const bodies = {};
for (const name of ICONS) {
  const data = getIconData(mynaui, name);
  if (!data) throw new Error(`Unknown MynaUI icon: "${name}"`);
  // 24-grid, stroke-based: the body keeps stroke="currentColor", so colour and
  // stroke width are still the caller's to set.
  bodies[name] = iconToSVG(data, { height: 24, width: 24 }).body;
}

const union = ICONS.map((n) => `  | "${n}"`).join("\n");
const entries = ICONS.map((n) => `  "${n}":\n    '${bodies[n].replace(/'/g, "\\'")}',`).join("\n");

writeFileSync(
  OUT,
  `/* AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
 *
 * MynaUI Icons (by Praveen Juge), resolved from the local @iconify-json/mynaui
 * package at generation time. Add a name to ICONS in the script and rerun
 * \`npm run gen:icons\`.
 */

import type { CSSProperties } from "react";

export type MynaIconName =
${union};

/* Path bodies only — a 24-grid viewBox is added by the component. Each keeps
 * stroke="currentColor", so an icon takes the colour of the text around it. */
const BODIES: Record<MynaIconName, string> = {
${entries}
};

/**
 * One icon, inlined as SVG. Safe in server and client components alike: no set
 * is imported at runtime, only the bodies above.
 *
 * \`strokeWidth\` overrides MynaUI's 1.5 — worth nudging down when an icon is
 * drawn large, or up at 14px and below where 1.5 goes faint.
 */
export function MynaIcon({
  name,
  size = 20,
  className,
  style,
  strokeWidth,
}: {
  name: MynaIconName;
  size?: number;
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
}) {
  const body = strokeWidth
    ? BODIES[name].replace(/stroke-width="[^"]*"/g, \`stroke-width="\${strokeWidth}"\`)
    : BODIES[name];

  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      width={size}
      height={size}
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
`,
  "utf8",
);

console.log(`Wrote ${ICONS.length} icons to ${OUT}`);
